# -*- coding: utf-8 -*-
"""Question_paper_generator.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KLlQ3VWZmMN1ydexenkV-H6g11uW5aGT
"""

!pip install groq pypdf

from google.colab import files

uploaded = files.upload()

import os

print(os.listdir())

from pypdf import PdfReader

reader = PdfReader("syllabus.pdf")

syllabus_text = ""

for page in reader.pages:
    text = page.extract_text()

    if text:
        syllabus_text += text

print(syllabus_text[:3000])

from groq import Groq

client = Groq(
    api_key="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"
)

prompt = f"""
You are an expert college professor.

Analyze the syllabus below and generate a NEW CIA-I Question Paper.

SYLLABUS:
{syllabus_text}

QUESTION PAPER PATTERN:

Part A:
9 Questions × 2 Marks = 18 Marks

Part B:
3 Questions × 14 Marks = 42 Marks

Rules:

1. Use only topics from syllabus.
2. Cover multiple units.
3. Do not repeat questions.
4. Maintain university exam style.
5. Include Part A and Part B headings.
6. Long questions should test understanding and application.
7. Output only the final question paper.

Generate the question paper now.
"""

response = client.chat.completions.create(
    model="llama3-70b-8192",
    messages=[
        {
            "role": "user",
            "content": prompt
        }
    ],
    temperature=0.7
)

generated_paper = response.choices[0].message.content

print(generated_paper)

try:
    response = client.chat.completions.create(
        model="llama-3.3-70b-versatile",
        messages=[
            {
                "role": "user",
                "content": "Hello"
            }
        ]
    )

    print(response.choices[0].message.content)

except Exception as e:
    print(e)

print(len(syllabus_text))

!apt-get install tesseract-ocr -y
!pip install pdf2image pytesseract pillow

from pdf2image import convert_from_path
import pytesseract

images = convert_from_path("syllabus.pdf")

syllabus_text = ""

for img in images:
    syllabus_text += pytesseract.image_to_string(img)

print(syllabus_text[:3000])
print("Length:", len(syllabus_text))

!apt-get update
!apt-get install -y poppler-utils

!apt-get install tesseract-ocr -y
!pip install pdf2image pytesseract pillow

from pdf2image import convert_from_path
import pytesseract

images = convert_from_path("syllabus.pdf")

syllabus_text = ""

for img in images:
    syllabus_text += pytesseract.image_to_string(img)

print(syllabus_text[:3000])
print("Length:", len(syllabus_text))

prompt = f"""
You are an expert university professor.

Generate a NEW CIA-I Question Paper based on the syllabus below.

SYLLABUS:
{syllabus_text[:5000]}

QUESTION PAPER PATTERN

Part A:
9 Questions × 2 Marks = 18 Marks

Part B:
3 Questions × 14 Marks = 42 Marks

Rules:
1. Use only syllabus topics.
2. Cover multiple units.
3. Do not repeat questions.
4. Follow university exam style.
5. Include Part A and Part B headings.
6. Long questions should test understanding and application.

Generate the complete question paper.
"""

response = client.chat.completions.create(
    model="llama-3.3-70b-versatile",
    messages=[
        {
            "role": "user",
            "content": prompt
        }
    ],
    temperature=0.7
)

generated_paper = response.choices[0].message.content

print(generated_paper)

prompt = f"""
You are a senior university professor.

Generate a COMPLETE CIA-I Question Paper for the subject
'Microprocessor and Embedded Systems'.

Use ONLY topics from this syllabus:

{syllabus_text[:4000]}

QUESTION PAPER PATTERN

PART A (9 x 2 = 18 Marks)

Generate exactly 9 short-answer questions.
Questions should be from different units.

PART B (3 x 14 = 42 Marks)

Generate exactly 3 long-answer questions.

Format:

10 a) Question ............. (14 Marks)

OR

10 b) Alternative Question ............. (14 Marks)

11 a) Question ............. (14 Marks)

OR

11 b) Alternative Question ............. (14 Marks)

12 a) Question ............. (14 Marks)

OR

12 b) Alternative Question ............. (14 Marks)

Rules:
- Use syllabus topics only.
- Long questions should be descriptive and analytical.
- Cover multiple units.
- Generate complete paper.
- Output only the question paper.
"""

response = client.chat.completions.create(
    model="llama-3.3-70b-versatile",
    messages=[
        {"role":"user","content":prompt}
    ],
    temperature=0.7
)

generated_paper = response.choices[0].message.content

print(generated_paper)

with open("Generated_Question_Paper.txt","w",encoding="utf-8") as f:
    f.write(generated_paper)

print("Question Paper Saved Successfully!")

from google.colab import files
files.download("Generated_Question_Paper.txt")